In [1]:
print('Multilayer Perceptron')

Multilayer Perceptron


In [20]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)
print(f'X: {X}')

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
print(f'weights_input_to_hidden: {weights_input_to_hidden}')
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))
print(f'weights_hidden_to_output: {weights_hidden_to_output}')

# test
# one column to calculate a resulting perceptron value, hiden perceptron 1
# is calcualted with X 1-4 and weight from matrix column 1
h1 = X[0] *weights_input_to_hidden[0,0] + X[1]*weights_input_to_hidden[1,0] + X[2]*weights_input_to_hidden[2,0] + X[3]*weights_input_to_hidden[3,0] 
print(f'h1:{h1}')
h1o = sigmoid(h1)
print(f'h1o (should 0.41492192) :{h1o}')


X: [ 0.49671415 -0.1382643   0.64768854  1.52302986]
weights_input_to_hidden: [[-0.02341534 -0.0234137   0.15792128]
 [ 0.07674347 -0.04694744  0.054256  ]
 [-0.04634177 -0.04657298  0.02419623]
 [-0.19132802 -0.17249178 -0.05622875]]
weights_hidden_to_output: [[-0.10128311  0.03142473]
 [-0.09080241 -0.14123037]
 [ 0.14656488 -0.02257763]]
h1:-0.3436549385998425
h1o (should 0.41492192) :0.41492192287919555


In [21]:

# TODO: Make a forward pass through the network

# Network size
# N_input = 4
# N_hidden = 3
# N_output = 2

# linear combination of x and weights        
h = np.dot(X, weights_input_to_hidden)
print(h)
hidden_layer_out = sigmoid(h)


print('Hidden-layer Output:')
print(hidden_layer_out)

# now from 3 hidden perceptrons to 2 outputs,
# weights matrix, has 1 column per output, here 2 columns,
# and row for each input, here 3 rows because of 3 inputs (hidden)
h2 = np.dot(hidden_layer_out, weights_hidden_to_output)
print(h2)
output_layer_out = sigmoid(h2)

print('Output-layer Output:')
print(output_layer_out)

[-0.34365494 -0.29801368  0.00097362]
Hidden-layer Output:
[0.41492192 0.42604313 0.5002434 ]
[-0.00739221 -0.05842573]
Output-layer Output:
[0.49815196 0.48539772]
